parameters:
#    ceremony_tracker.example.class: SensioLabs\CeremonyTrackerBundle\Example

services:
#    ceremony_tracker.example:
#        class: %ceremony_tracker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
